name: CI — Build & Test (Maven)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build & run tests
        run: |
          mvn -B -q -DskipTests=false test
          mvn -B -q -DskipTests=false verify

      - name: Upload surefire test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports
          path:
            **/target/surefire-reports/**