name: CI — Build & Test (Maven)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Make mvnw executable (if present)
        run: |
          if [ -f mvnw ]; then chmod +x mvnw; fi

      - name: Build & run tests (H2 test profile)
        run: |
          ./mvnw -B -ntp -Dspring.profiles.active=test -DskipTests=false verify

      - name: Print surefire reports on failure
        if: failure()
        run: |
          echo "Dumping surefire reports (if any)"
          for f in $(ls -1 **/target/surefire-reports/*.txt 2>/dev/null || true); do
            echo "---- $f ----"
            cat "$f"
            echo
          done

      - name: Upload surefire test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports
          path: "**/target/surefire-reports/**"
